### PR TITLE
Django 1.8 compatibility 

### PR DESCRIPTION
**Pull request by nicholasserra**
#### What's this PR do?
Support Django 1.8

- Added steps to test against Django 1.8
- Silenced some noisy logging in tests

### CODE REVIEW

**Comment by nicholasserra** [comment]
No longer WIP, no additional changes were needed. I want to beef up test coverage in another PR.

**Comment by frankwiles** [comment]
Should we do a release?

**Comment by pydanny** [comment]
Once we support Django 1.9 then I think a release is in order. :smile:

**Comment by nicholasserra** [comment]
Agreed ^

**Pull request merged**
