### PR TITLE
Make middleware keep track of the next query parameter and add a test for it

### PR DESCRIPTION
**Pull request by blag**

### CODE REVIEW

**Comment by nicholasserra** [comment]
Does this also work if they don't provide a redirect attribute?

**Comment by blag** [comment]
The commit message is a little misnamed, I should have called it the `name` parameter. And if I understand your questions correctly, yes, because this pulls the `path_info` from the request and applies it to the redirect parameter in the URL.

Going to a URL without a `next` parameter is tested on line [45/53](https://github.com/revsys/django-tos/pull/29/files#diff-4ba515e45e935efd224d93e06f8de791R53), which correctly redirects to the confirm view including a created `next` parameter.

**Comment by blag** [comment]
Fixed the failing tests, the commit message, and the PR title. This should be ready to merge.

**Comment by nicholasserra** [comment]
After taking a real look at this, i'm realizing my question didn't make much sense. So apologies, and thanks for clarifying. Thanks for your continued work on this !

**Pull request merged**
