### PR TITLE
Fix and tests for cache invalidation issue

### PR DESCRIPTION
**Pull request by nicholasserra**
Fixes #38 #40

### CODE REVIEW

**Comment by nicholasserra** [comment]
@frankwiles Not sure how this took so long to catch, but the middleware option for this package wasn't working until this fix. If you find a spare second a new version should probably go out. Thanks!

**Comment by frankwiles** [comment]
Nice catch! Just released v0.9.0 to pypi

**Comment by nicholasserra** [comment]
Thanks! Do you have a local change for the version bump that needs pushed to master?

**Comment by frankwiles** [comment]
Doh! Forgot to push, it's there now.

**Pull request merged**
